
[types]

	[types.wood_type]

		[types.wood_type.environmental]
			willow = true
			cherry = true
			wisteria = true
			pine = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			kousa = true
			aspen = true
			grimwood = true
			laurel = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true

		[types.wood_type.quark]
			bamboo = true
			azalea = false
			blossom = false
			ancient = false

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.hexcasting]
			edified = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.deeperdarker]
			echo = true

	[types.leaves_type]

		[types.leaves_type.environmental]
			willow = true
			cherry = true
			hibiscus = true
			pine = true
			cheerful_cherry = true
			moody_cherry = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			kousa = true
			aspen = true
			grimwood = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			currant = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.quark]
			blue_blossom = false
			lavender_blossom = false
			orange_blossom = false
			pink_blossom = false
			yellow_blossom = false
			red_blossom = false
			ancient = false

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.hexcasting]
			amethyst_edified = true
			aventurine_edified = true
			citrine_edified = true

		[types.leaves_type.deeperdarker]
			echo = true

[entries]

	[entries.wood_type]

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.woodworks]
			beehive = true
			ladder = true
			boards = true
			bookshelf = true
			trapped_chest = true
			chest = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			vertical_planks = false
			chest = false
			ladder = false
			hollow_log = false
			post = true
			trapped_chest = false
			bookshelf = false
			stripped_post = true

		[entries.wood_type.another_furniture]
			table = true
			shelf = true
			drawer = true
			shutter = true
			planter_box = true
			bench = true
			chair = true

		[entries.wood_type.infinitybuttons]
			plank_secret_button = true
			large_button = true

	[entries.leaves_type]

		[entries.leaves_type.woodworks]
			leaf_pile = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = false

